#!/bin/bash

source /usr/local/JSBach/conf/variables.conf


while read -r ordre
do
	if [[ -n $ordre ]] then
		
		Comando=$(echo "$ordre" | awk '{print $1}') 
		Arguments="${ordre#*$Comando }"
				
		case "$Comando" in
			"enrutar")  
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/enrutar $Arguments"
			    ;;
			"ifwan")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/ifwan $Arguments"
			    ;;
			"bridge")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/bridge $Arguments"
			    ;;			    
			"tallafocs")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/tallafocs $Arguments"
			    ;;
			"dmz")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/dmz $Arguments"
			    ;;
			"switch")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/switch $Arguments"
			    ;;			
			"wifi")
			    eval "$DIR/$PROJECTE/$DIR_SCRIPTS/wifi $Arguments"
			    ;;			
			*) 
			    echo "CLI Error en l'argument $Comando $Arguments"
			    ;;
		esac	
	fi
	
	echo "final"
done;
