#!/bin/bash

source /usr/local/JSBach/conf/variables.conf
source $DIR/$PROJECTE/$DIR_CONF/$CONF_IFWAN

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
  if [ "$(fnc_estat)" == "$ACTIVAT" ]
	then
		echo "<h3>Ja esta activa</h3>"
		exit 1
	fi
	echo "Iniciar"	
	echo 1 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -A POSTROUTING -o $IFW_IFWAN -j MASQUERADE
	
}

fnc_aturar()
{
	echo "Aturar"
	echo 0 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -D POSTROUTING -o $IFW_IFWAN -j MASQUERADE
}


fnc_estat()
{

	if [ "$(cat /proc/sys/net/ipv4/ip_forward)" -eq 1 ] && iptables -t nat -C POSTROUTING -o "$IFW_IFWAN" -j MASQUERADE 2>/dev/null; then
	    echo "$ACTIVAT"
	else
	    echo "$DESACTIVAT"	
	fi
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_iniciar  $@
    ;;
  aturar)
    fnc_aturar	$@
    ;; 
  estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac


