#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
	fnc_aturar
	echo "Iniciar"	
		
	
	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"); do
	    nom=$(echo "$linia"|cut -d';' -f1)
	    ip=$(echo "$linia"|cut -d';' -f3)
	    iptables -N $nom 2>/dev/null || iptables -F $nom
	    iptables -A FORWARD -s $ip -j $nom	    
	done
	
	iptables -N ports_wls
	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$PORTS_WLS"); do
	    protocol=$(echo "$linia"|cut -d';' -f1)
	    num_port=$(echo "$linia"|cut -d';' -f2)
	    iptables -A ports_wls -p $protocol --dport $num_port -j ACCEPT	    
	done
	iptables -A ports_wls -j DROP

	##################################
	# Chains INPUT per VLAN
	##################################
	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"); do
    nom=$(echo "$linia" | cut -d';' -f1)
    ip=$(echo "$linia" | cut -d';' -f3)

    iptables -N INPUT_$nom
    iptables -A INPUT -s "$ip" -j INPUT_$nom
done
	#VLAN ADMIN
	iptables -F INPUT_${VLAN_ADMIN_NAME}
	iptables -A INPUT_${VLAN_ADMIN_NAME} -j ACCEPT

	#VLAN DMZ
	iptables -F INPUT_${VLAN_DMZ_NAME}
	iptables -A INPUT_${VLAN_DMZ_NAME} -p tcp --dport 80 -j DROP
	iptables -A INPUT_${VLAN_DMZ_NAME} -p tcp --dport 443 -j DROP
	iptables -A INPUT_${VLAN_DMZ_NAME} -j ACCEPT

}

fnc_aturar()
{
	echo "Aturar"
	iptables -F
	iptables -X
	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	
	
	resultat=$($DIR/$PROJECTE/$DIR_SCRIPTS/enrutar estat)

	# Comprovem si conté la paraula "ACTIVAT"
	echo "$resultat" | grep -q "$ACTIVAT"

	if [ $? -eq 0 ]; then
		iptables -t nat -F 
		iptables -t nat -X
		$DIR/$PROJECTE/$DIR_SCRIPTS/enrutar iniciar
	else
		iptables -t nat -F 
		iptables -t nat -X
	fi	
	iptables -F INPUT
iptables -P INPUT ACCEPT

}


fnc_configurar()
{	
	
	echo "Configuracio"
	
	ARG_1=$1
	shift
			
	# Fem switch per executar la funció que toca
	case "$ARG_1" in
	  desconnectar)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        vid=$( echo $linia | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
		    iptables -F $nom
		        # IPs privilegiades
		     	for ipwls in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"| grep "^$vid;"); do
			    ip=$(echo "$ipwls"|cut -d';' -f2)
			    mac=$(echo "$ipwls"|cut -d';' -f3)
			    iptables -A $nom   -s $ip -m mac --mac-source $mac -j ACCEPT 
			done

		    iptables -A $nom -j DROP
		fi
	  	;;
	  connectar)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
		else
			iptables -F $nom
		fi	        
	  	;;
          connectar_port_wls)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        vid=$( echo $linia | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
		else
			iptables -F $nom
		 	# IPs privilegiades
			for ipwls in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"| grep "^$vid;"); do
			    ip=$(echo "$ipwls"|cut -d';' -f2)
			    mac=$(echo "$ipwls"|cut -d';' -f3)
			    iptables -A $nom   -s $ip -m mac --mac-source $mac -j ACCEPT 
			done
			
			iptables -A $nom -j ports_wls
			
		fi	        
	  	;;
		##################################
		# INPUT firewall
##################################

	input_allow_router)
    linia=$(grep ";$1;" "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF")
    nom=$(echo "$linia" | cut -d';' -f1)

    iptables -F INPUT_$nom
    iptables -A INPUT_$nom -j ACCEPT
	;;

	input_block_router)
    linia=$(grep ";$1;" "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF")
    nom=$(echo "$linia" | cut -d';' -f1)

    iptables -F INPUT_$nom
    iptables -A INPUT_$nom -p tcp --dport 80 -j DROP
    iptables -A INPUT_$nom -p tcp --dport 443 -j DROP
    iptables -A INPUT_$nom -j ACCEPT
	;;

	input_minimal)
    linia=$(grep ";$1;" "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF")
    nom=$(echo "$linia" | cut -d';' -f1)

    iptables -F INPUT_$nom
    iptables -A INPUT_$nom -p icmp -j ACCEPT
    iptables -A INPUT_$nom -p udp --dport 67:68 -j ACCEPT
    iptables -A INPUT_$nom -j DROP
	;;

	input_drop_all)
    linia=$(grep ";$1;" "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF")
    nom=$(echo "$linia" | cut -d';' -f1)

    iptables -F INPUT_$nom
    iptables -A INPUT_$nom -j DROP
	;;

	  *)
	        echo "Error  argumnets conectar, desconectar"
	        ;;
	esac	
	
}


fnc_estat()
{	
	if [ $# -eq 0 ]; then
		 #echo "$ACTIVAT"
		 #echo "$DESACTIVAT"
		 echo MAIN
		 iptables -nvL --line-numbers
		 echo
		 echo
		 echo NAT	 
		 iptables -t nat -nvL --line-numbers
		 exit 1
	fi
	
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
		     	if iptables -C $nom -j DROP 2>/dev/null; then
			    echo "DESCONNECTADA"
			else
			    echo "CONNECTADA"
			fi 
		fi
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_iniciar  $@
    ;;
  aturar)
    fnc_aturar	$@
    ;; 
  configurar) 
    fnc_configurar $@
    ;;
  estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac


